const draws: {
  year: number;
  relations: {
    [K in string]: string;
  };
}[] = [
  {
    year: 2018,
    relations: {
      "alexandre-sarran": "denis-blum",
      "amy-haddad": "enora-corlay",
      "anne-julien": "helene-bazille",
      "caedmon-haddad": "timothee-vang",
      "david-bourgeois": "mailys-blum",
      "denis-blum": "amy-haddad",
      "dimitri-cobb": "stephane-hamelin",
      "enora-corlay": "marie-noelle-gerber",
      "etienne-gerber": "lenora-haddad",
      "etienne-sarran": "ivan-hamelin",
      "fabrice-lingois": "alexandre-sarran",
      "gilles-campoy": "jonah-haddad",
      "helene-bazille": "etienne-gerber",
      "ivan-hamelin": "marie-julien",
      "jonah-haddad": "soohyun-vang",
      "kalhou-vang": "dimitri-cobb",
      "karine-comte": "yvette-campoy",
      "lenora-haddad": "linda-hamelin",
      "linda-hamelin": "matthieu-sarran",
      "mailys-blum": "anne-julien",
      "margaret-haddad": "etienne-sarran",
      "marie-julien": "vallouise-sarran",
      "marie-noelle-gerber": "suzanne-sarran",
      "matthieu-sarran": "gilles-campoy",
      "pascal-haddad": "theotime-julien",
      "solange-de-melo": "kalhou-vang",
      "soohyun-vang": "solange-de-melo",
      "stephane-hamelin": "timothee-sarran",
      "suzanne-sarran": "karine-comte",
      "theotime-julien": "caedmon-haddad",
      "timothee-sarran": "david-bourgeois",
      "timothee-vang": "margaret-haddad",
      "vallouise-sarran": "pascal-haddad",
      "yvette-campoy": "fabrice-lingois",
    },
  },
  {
    year: 2019,
    relations: {
      "alexandre-sarran": "qiqi-zhu",
      "amelie-fournier": "toyese-oyegoke",
      "annie-tshika": "suzanne-sarran",
      "charlene-picq": "yvette-campoy",
      "denis-blum": "timothee-sarran",
      "dimitri-cobb": "jung-yeon-gosselin",
      "dwight-bornes": "stephane-hamelin",
      "enora-corlay": "nathalie-merlano",
      "etienne-gerber": "enora-corlay",
      "etienne-sarran": "marie-julien",
      "fabrice-lingois": "linda-hamelin",
      "flora-julien": "laetitia-stauffer",
      "gilles-campoy": "laetitia-grare",
      "helene-bazille": "amelie-fournier",
      "isaque-carreto": "matthieu-sarran",
      "ivan-hamelin": "vallouise-sarran",
      "jean-francois-maniere": "helene-bazille",
      "jeronimo-avellaneda": "etienne-sarran",
      "joshua-sims": "yi-hsuan-chen",
      "jung-yeon-gosselin": "jean-francois-maniere",
      "kalhou-vang": "charlene-picq",
      "karine-comte": "denis-blum",
      "laetitia-grare": "etienne-gerber",
      "laetitia-stauffer": "joshua-sims",
      "linda-hamelin": "thierry-comte",
      "mailys-blum": "teresa-carreto",
      "marie-noelle-gerber": "gilles-campoy",
      "marie-julien": "ivan-hamelin",
      "matthieu-sarran": "flora-julien",
      "mireille-yoyotte-landry": "orlane-batman",
      "nathalie-merlano": "mailys-blum",
      "orlane-batman": "pierrick-fournier",
      "pierrick-fournier": "dwight-bornes",
      "qiqi-zhu": "soohyun-vang",
      "rafaella-bartz-pena": "karine-comte",
      "soohyun-vang": "annie-tshika",
      "stephane-hamelin": "marie-noelle-gerber",
      "suzanne-sarran": "trina-collet",
      "tehele-mpassi": "kalhou-vang",
      "teresa-carreto": "mireille-yoyotte-landry",
      "thierry-comte": "dimitri-cobb",
      "timothee-sarran": "vincent-collet",
      "tom-kristanek": "fabrice-lingois",
      "toyese-oyegoke": "tom-kristanek",
      "trina-collet": "isaque-carreto",
      "vallouise-sarran": "jeronimo-avellaneda",
      "vincent-collet": "rafaella-bartz-pena",
      "yi-hsuan-chen": "tehele-mpassi",
      "yvette-campoy": "alexandre-sarran",
    },
  },
  {
    year: 2021,
    relations: {
      "alexandre-sarran": "daniel-le-gal",
      "etienne-sarran": "yahel-caparros",
      "suzanne-sarran": "yvette-campoy",
      "timothee-sarran": "lydie-exbrayat",
      "vallouise-sarran": "jeronimo-avellaneda",
      "augustin-sarran": "madele-bazille",
      "violette-sarran": "lois-bazille",
      "helene-bazille": "sabine-chanel",
      "denis-blum": "qiqi-zhu",
      "elia-grace-exbrayat": "vallouise-sarran",
      "elona-caparros": "etienne-sarran",
      "gilles-campoy": "myriam-caparros",
      "hyun-joo-exbrayat": "kenneth-ziegler",
      "laurent-caparros": "caryn-di-gena",
      "linda-hamelin": "laurent-caparros",
      "lydie-exbrayat": "elona-caparros",
      "mailys-blum": "marie-jo-descheemaecker",
      "myriam-caparros": "suzanne-sarran",
      "stephane-hamelin": "florian-vincenzi",
      "timothee-exbrayat": "timothee-sarran",
      "yahel-caparros": "timothee-exbrayat",
      "fabrice-lingois": "helene-bazille",
      "lois-bazille": "augustin-sarran",
      "madele-bazille": "violette-sarran",
      "charlene-picq": "yi-hsuan-chen",
      "florian-vincenzi": "marc-descheemaecker",
      "gabrielle-ziegler": "sophie-vincenzi",
      "jean-francois-chanel": "lars-fracheboud",
      "jean-francois-maniere": "gilles-campoy",
      "kenneth-ziegler": "lucy-nemoz",
      "laetitia-stauffer": "jeanne-guilhot",
      "marc-descheemaecker": "francois-risson",
      "marie-jo-descheemaecker": "amaury-francais",
      "nathalie-merlano": "jean-francois-maniere",
      "qiqi-zhu": "fabrice-lingois",
      "sabine-chanel": "laetitia-stauffer",
      "sophie-vincenzi": "charlene-picq",
      "yi-hsuan-chen": "nathalie-merlano",
      "yvette-campoy": "denis-blum",
      "amaury-francais": "gabrielle-ziegler",
      "aurelie-charles": "linda-hamelin",
      "caryn-di-gena": "stephane-hamelin",
      "colin-cachard": "jean-francois-chanel",
      "daniel-le-gal": "hyun-joo-exbrayat",
      "elsa-lelieu": "mathilde-portmann",
      "francois-risson": "naomi-vigne",
      "jeanne-guilhot": "lycia-francais",
      "jeronimo-avellaneda": "elia-grace-exbrayat",
      "laetitia-calabria": "colin-cachard",
      "lars-fracheboud": "alexandre-sarran",
      "lucy-nemoz": "laetitia-calabria",
      "lycia-francais": "aurelie-charles",
      "mathilde-portmann": "mailys-blum",
      "naomi-vigne": "elsa-lelieu",
    },
  },
];

export default draws;
