const persons: {
  slug: string;
  firstName: string;
  lastName: string;
  gender: "male" | "female";
  email?: string | undefined;
  age?: "6-9" | "10-13" | "14-17" | "18+";
  archived?: boolean;
}[] = [
  {
    slug: "alexandre-sarran",
    email: "alexandre.sarran@egliselyongerland.org",
    firstName: "Alexandre",
    lastName: "Sarran",
    gender: "male",
  },
  {
    slug: "amaury-francais",
    email: "fra.amaury@gmail.com",
    firstName: "Amaury",
    lastName: "Français",
    gender: "male",
    archived: true,
  },
  {
    slug: "amelie-fournier",
    firstName: "Amélie",
    lastName: "Fournier",
    gender: "female",
    archived: true,
  },
  {
    slug: "amy-haddad",
    firstName: "Amy",
    lastName: "Haddad",
    gender: "female",
    archived: true,
  },
  {
    slug: "anne-julien",
    firstName: "Anne",
    lastName: "Julien",
    gender: "female",
    archived: true,
  },
  {
    slug: "annie-tshika",
    firstName: "Annie",
    lastName: "Tshika",
    gender: "female",
    archived: true,
  },
  {
    slug: "augustin-sarran",
    email: "alexsarran@gmail.com",
    firstName: "Augustin",
    lastName: "Sarran",
    gender: "male",
    age: "6-9",
    archived: true,
  },
  {
    slug: "aurelie-charles",
    email: "aurelie.wattiau@laposte.net",
    firstName: "Aurélie",
    lastName: "Charles",
    gender: "female",
    archived: true,
  },
  {
    slug: "caedmon-haddad",
    firstName: "Caedmon",
    lastName: "Haddad",
    gender: "male",
    age: "14-17",
    archived: true,
  },
  {
    slug: "caryn-di-gena",
    email: "caryn.digena@efca.org",
    firstName: "Caryn",
    lastName: "DiGena",
    gender: "female",
    archived: true,
  },
  {
    slug: "charlene-picq",
    email: "picqcharlene.cnp@gmail.com",
    firstName: "Charlène",
    lastName: "Picq",
    gender: "female",
    archived: true,
  },
  {
    slug: "charline-jacobs",
    email: "charline.binckly@live.fr",
    firstName: "Charline",
    lastName: "Jacobs",
    gender: "female",
  },
  {
    slug: "colin-cachard",
    email: "colin-cachard@orange.fr",
    firstName: "Colin",
    lastName: "Cachard",
    gender: "male",
    archived: true,
  },
  {
    slug: "daniel-le-gal",
    email: "daniel.legal.00@gmail.com",
    firstName: "Daniel",
    lastName: "Le Gal",
    gender: "male",
    archived: true,
  },
  {
    slug: "david-bourgeois",
    firstName: "David",
    lastName: "Bourgeois",
    gender: "male",
    archived: true,
  },
  {
    slug: "denis-blum",
    email: "blumdenis@aol.com",
    firstName: "Denis",
    lastName: "Blum",
    gender: "male",
  },
  {
    slug: "dimitri-cobb",
    firstName: "Dimitri",
    lastName: "Cobb",
    gender: "male",
    archived: true,
  },
  {
    slug: "dwight-bornes",
    firstName: "Dwight",
    lastName: "Bornes",
    gender: "male",
    archived: true,
  },
  {
    slug: "elia-grace-exbrayat",
    email: "exbrayatpv@gmail.com",
    firstName: "Elia-Grace",
    lastName: "Exbrayat",
    gender: "female",
    age: "10-13",
    archived: true,
  },
  {
    slug: "elona-caparros",
    email: "elona.caparros@icloud.com",
    firstName: "Elona",
    lastName: "Caparros",
    gender: "female",
    age: "14-17",
  },
  {
    slug: "elsa-lelieu",
    email: "elsamon@hotmail.fr",
    firstName: "Elsa",
    lastName: "Lelieu",
    gender: "female",
    archived: true,
  },
  {
    slug: "enora-corlay",
    firstName: "Énora",
    lastName: "Corlay",
    gender: "female",
    archived: true,
  },
  {
    slug: "etienne-gerber",
    firstName: "Étienne",
    lastName: "Gerber",
    gender: "male",
    archived: true,
  },
  {
    slug: "etienne-sarran",
    email: "etiennesarran@gmail.com",
    firstName: "Etienne",
    lastName: "Sarran",
    gender: "male",
    age: "14-17",
    archived: true,
  },
  {
    slug: "fabrice-lingois",
    email: "lingois.fabrice@hotmail.fr",
    firstName: "Fabrice",
    lastName: "Lingois",
    gender: "male",
    archived: true,
  },
  {
    slug: "flora-julien",
    firstName: "Flora",
    lastName: "Julien",
    gender: "female",
    archived: true,
  },
  {
    slug: "florian-vincenzi",
    email: "vincenzi.florian@gmail.com",
    firstName: "Florian",
    lastName: "Vincenzi",
    gender: "male",
  },
  {
    slug: "francois-risson",
    email: "francoisrisson@gmail.com",
    firstName: "François",
    lastName: "Risson",
    gender: "male",
  },
  {
    slug: "gabrielle-ziegler",
    email: "gabi@zieglers.org",
    firstName: "Gabriëlle",
    lastName: "Ziegler",
    gender: "female",
  },
  {
    slug: "gilles-campoy",
    email: "gillescampoy42@gmail.com",
    firstName: "Gilles",
    lastName: "Campoy",
    gender: "male",
  },
  {
    slug: "helene-bazille",
    email: "helene@bazille.fr",
    firstName: "Hélène",
    lastName: "Bazille",
    gender: "female",
  },
  {
    slug: "hyun-joo-exbrayat",
    email: "exbrayatpv@gmail.com",
    firstName: "Hyun-Joo",
    lastName: "Exbrayat",
    gender: "female",
    archived: true,
  },
  {
    slug: "isaque-carreto",
    firstName: "Isaque",
    lastName: "Carreto",
    gender: "male",
    archived: true,
  },
  {
    slug: "ivan-hamelin",
    firstName: "Ivan",
    lastName: "Hamelin",
    gender: "male",
    age: "14-17",
    archived: true,
  },
  {
    slug: "jean-francois-chanel",
    email: "sabine.chanel@laposte.net",
    firstName: "Jean-François",
    lastName: "Chanel",
    gender: "female",
  },
  {
    slug: "jean-francois-maniere",
    email: "jf.maniere@orange.fr",
    firstName: "Jean-François",
    lastName: "Manière",
    gender: "male",
    archived: true,
  },
  {
    slug: "jeanne-guilhot",
    email: "Guilhot.jeanne@gmail.com",
    firstName: "Jeanne",
    lastName: "Guilhot",
    gender: "female",
    archived: true,
  },
  {
    slug: "jeronimo-avellaneda",
    email: "avellanedajeronimo08@gmail.com",
    firstName: "Jerónimo",
    lastName: "Avellaneda Merlano",
    gender: "male",
    age: "14-17",
  },
  {
    slug: "jonah-haddad",
    firstName: "Jonah",
    lastName: "Haddad",
    gender: "male",
    archived: true,
  },
  {
    slug: "joshua-jacobs",
    email: "joshua.m.jacobs@gmail.com",
    firstName: "Joshua",
    lastName: "Jacobs",
    gender: "male",
  },
  {
    slug: "joshua-sims",
    firstName: "Joshua",
    lastName: "Sims",
    gender: "male",
  },
  {
    slug: "jung-yeon-gosselin",
    firstName: "Jung-Yeon",
    lastName: "Gosselin",
    gender: "female",
    archived: true,
  },
  {
    slug: "kalhou-vang",
    firstName: "Kalhou",
    lastName: "Vang",
    gender: "male",
  },
  {
    slug: "karine-comte",
    firstName: "Karine",
    lastName: "Comte",
    gender: "female",
    archived: true,
  },
  {
    slug: "kenneth-ziegler",
    email: "ken@zieglers.org",
    firstName: "Kenneth",
    lastName: "Ziegler",
    gender: "male",
  },
  {
    slug: "laetitia-calabria",
    email: "calabrialaetitia@gmail.com",
    firstName: "Laetitia",
    lastName: "Calabria",
    gender: "female",
    archived: true,
  },
  {
    slug: "laetitia-grare",
    firstName: "Laetitia",
    lastName: "Grare",
    gender: "female",
    archived: true,
  },
  {
    slug: "laetitia-stauffer",
    email: "staufferlaetitia@gmail.com",
    firstName: "Laetitia",
    lastName: "Stauffer",
    gender: "female",
    archived: true,
  },
  {
    slug: "lars-fracheboud",
    email: "highestpeak.fr@gmail.com",
    firstName: "Lars",
    lastName: "Fracheboud",
    gender: "male",
    archived: true,
  },
  {
    slug: "laurent-caparros",
    email: "lc6926@gmail.com",
    firstName: "Laurent",
    lastName: "Caparros",
    gender: "male",
  },
  {
    slug: "lenora-haddad",
    firstName: "Lenora",
    lastName: "Haddad",
    gender: "female",
    archived: true,
  },
  {
    slug: "linda-hamelin",
    email: "lzhamelin@gmail.com",
    firstName: "Linda",
    lastName: "Hamelin",
    gender: "female",
    archived: true,
  },
  {
    slug: "lois-bazille",
    email: "helene@bazille.fr",
    firstName: "Loïs",
    lastName: "Bazille",
    gender: "female",
    age: "6-9",
  },
  {
    slug: "lois-vang",
    email: "kalhouvang@gmail.com",
    firstName: "Loïs",
    lastName: "Vang",
    gender: "female",
    age: "6-9",
  },
  {
    slug: "lucy-nemoz",
    email: "lucynemoz@gmail.com",
    firstName: "Lucy",
    lastName: "Nemoz",
    gender: "female",
    archived: true,
  },
  {
    slug: "lycia-francais",
    email: "lycia.francais@gmail.com",
    firstName: "Lycia",
    lastName: "French",
    gender: "female",
    archived: true,
  },
  {
    slug: "lydie-exbrayat",
    email: "exbrayatpv@gmail.com",
    firstName: "Lydie",
    lastName: "Exbrayat",
    gender: "female",
    age: "14-17",
    archived: true,
  },
  {
    slug: "madele-bazille",
    email: "helene@bazille.fr",
    firstName: "Madèle",
    lastName: "Bazille",
    gender: "female",
    age: "6-9",
  },
  {
    slug: "magdiel-fumero-darias",
    email: "magfumdar@gmail.com",
    firstName: "Magdiel",
    lastName: "Fumero Darias",
    gender: "male",
  },
  {
    slug: "mailys-blum",
    email: "mailysvenet@gmail.com",
    firstName: "Mailys",
    lastName: "Blum",
    gender: "female",
    archived: true,
  },
  {
    slug: "marc-descheemaecker",
    email: "marc.descheemaecker3@gmail.com",
    firstName: "Marc",
    lastName: "Descheemaecker",
    gender: "male",
    archived: true,
  },
  {
    slug: "margaret-haddad",
    firstName: "Margaret",
    lastName: "Haddad",
    gender: "female",
    age: "10-13",
    archived: true,
  },
  {
    slug: "marie-jo-descheemaecker",
    email: "mariejoseedesch@gmail.com",
    firstName: "Marie-Jo",
    lastName: "Descheemaecker",
    gender: "female",
    archived: true,
  },
  {
    slug: "marie-julien",
    firstName: "Marie",
    lastName: "Julien",
    gender: "female",
    age: "10-13",
    archived: true,
  },
  {
    slug: "marie-noelle-gerber",
    firstName: "Marie-Noëlle",
    lastName: "Gerber",
    gender: "female",
  },
  {
    slug: "mathilde-portmann",
    email: "portmannmathilde@yahoo.fr",
    firstName: "Mathilde",
    lastName: "Portmann",
    gender: "female",
  },
  {
    slug: "matthieu-sarran",
    firstName: "Matthieu",
    lastName: "Sarran",
    gender: "male",
    archived: true,
  },
  {
    slug: "mireille-yoyotte-landry",
    firstName: "Mireille",
    lastName: "Yoyotte Landry",
    gender: "female",
    archived: true,
  },
  {
    slug: "myriam-caparros",
    email: "myriamcap@free.fr",
    firstName: "Myriam",
    lastName: "Caparros",
    gender: "female",
  },
  {
    slug: "naomi-vigne",
    email: "nao.vigne@gmail.com",
    firstName: "Naomi",
    lastName: "Vigné",
    gender: "female",
    archived: true,
  },
  {
    slug: "nathalie-merlano",
    email: "nathaliemerlano@hotmail.com",
    firstName: "Nathalie",
    lastName: "Merlano Rey",
    gender: "female",
  },
  {
    slug: "orlane-batman",
    firstName: "Orlane",
    lastName: "Batman",
    gender: "female",
    archived: true,
  },
  {
    slug: "pascal-haddad",
    firstName: "Pascal",
    lastName: "Haddad",
    gender: "male",
    age: "10-13",
    archived: true,
  },
  {
    slug: "pierrick-fournier",
    firstName: "Pierrick",
    lastName: "Fournier",
    gender: "male",
    archived: true,
  },
  {
    slug: "qiqi-zhu",
    email: "qiqizhu2020@outlook.com",
    firstName: "Qiqi",
    lastName: "Zhu",
    gender: "female",
    archived: true,
  },
  {
    slug: "rafaella-bartz-pena",
    firstName: "Rafaella",
    lastName: "Bartz Pena",
    gender: "female",
    archived: true,
  },
  {
    slug: "raphaelle-perret",
    email: "raphaelle.perret@gmail.com",
    firstName: "Raphaelle",
    lastName: "Perret",
    gender: "female",
  },
  {
    slug: "sabine-chanel",
    email: "sabine.chanel@laposte.net",
    firstName: "Sabine",
    lastName: "Chanel",
    gender: "female",
  },
  {
    slug: "solange-de-melo",
    firstName: "Solange",
    lastName: "De Melo",
    gender: "female",
    archived: true,
  },
  {
    slug: "soohyun-vang",
    firstName: "Soohyun",
    lastName: "Vang",
    gender: "female",
  },
  {
    slug: "sophie-vincenzi",
    email: "sophie.dellacorte@outlook.com",
    firstName: "Sophie",
    lastName: "Vincenzi",
    gender: "female",
    archived: true,
  },
  {
    slug: "stephane-hamelin",
    email: "hamelinsteph@gmail.com",
    firstName: "Stéphane",
    lastName: "Hamelin",
    gender: "male",
  },
  {
    slug: "suzanne-sarran",
    email: "sarransuzanne@gmail.com",
    firstName: "Suzanne",
    lastName: "Sarran",
    gender: "female",
    archived: true,
  },
  {
    slug: "tehele-mpassi",
    firstName: "Tehele",
    lastName: "Mpassi",
    gender: "male",
    archived: true,
  },
  {
    slug: "teresa-carreto",
    firstName: "Teresa",
    lastName: "Carreto",
    gender: "female",
    archived: true,
  },
  {
    slug: "theotime-julien",
    firstName: "Théotime",
    lastName: "Julien",
    gender: "male",
    age: "14-17",
    archived: true,
  },
  {
    slug: "thierry-comte",
    firstName: "Thierry",
    lastName: "Comte",
    gender: "male",
    archived: true,
  },
  {
    slug: "timothee-exbrayat",
    email: "exbrayatpv@gmail.com",
    firstName: "Timothée",
    lastName: "Exbrayat",
    gender: "male",
    age: "14-17",
    archived: true,
  },
  {
    slug: "timothee-sarran",
    email: "sarrantimothee@gmail.com",
    firstName: "Timothée",
    lastName: "Sarran",
    gender: "male",
    age: "14-17",
    archived: true,
  },
  {
    slug: "timothee-vang",
    firstName: "Timothée",
    lastName: "Vang",
    gender: "male",
    age: "10-13",
  },
  {
    slug: "tom-kristanek",
    firstName: "Tom",
    lastName: "Kristanek",
    gender: "male",
    archived: true,
  },
  {
    slug: "toyese-oyegoke",
    firstName: "Toyese",
    lastName: "Oyegoke",
    gender: "male",
    archived: true,
  },
  {
    slug: "trina-collet",
    firstName: "Trina",
    lastName: "Collet",
    gender: "female",
    archived: true,
  },
  {
    slug: "vallouise-sarran",
    email: "Vallouisesarran@gmail.com",
    firstName: "Vallouise",
    lastName: "Sarran",
    gender: "female",
    age: "10-13",
    archived: true,
  },
  {
    slug: "vincent-collet",
    firstName: "Vincent",
    lastName: "Collet",
    gender: "male",
    archived: true,
  },
  {
    slug: "violette-sarran",
    email: "alexsarran@gmail.com",
    firstName: "Violette",
    lastName: "Sarran",
    gender: "female",
    age: "6-9",
    archived: true,
  },
  {
    slug: "yahel-caparros",
    email: "myriamcap@free.fr",
    firstName: "Yahel",
    lastName: "Caparros",
    gender: "male",
    age: "14-17",
  },
  {
    slug: "yi-hsuan-chen",
    email: "artist5818@gmail.com",
    firstName: "Yi-Hsuan",
    lastName: "Chen",
    gender: "female",
  },
  {
    slug: "yvette-campoy",
    email: "yvettecampoy@hotmail.com",
    firstName: "Yvette",
    lastName: "Campoy",
    gender: "female",
  },
];

export default persons;
